Repository scalameta/scalameta, pull requests merged in 2018-03, with the labels that each got.

#1394 Metacp cache, take two
  .scalafmt.conf
  build.sbt
  langmeta/langmeta/jvm/src/main/scala/org/langmeta/internal/io/PlatformFileIO.scala
  langmeta/langmeta/shared/src/main/scala/org/langmeta/io/Multipath.scala
  scalameta/testkit/src/main/scala/scala/meta/testkit/DiffAssertions.scala
  semanticdb/integration/src/main/java/com/javacp/Javacp.java
  semanticdb/integration/src/main/java/com/javacp/Logger.java
  semanticdb/integration/src/main/scala/example/Javacp.scala
  semanticdb/metac/src/main/scala/scala/meta/cli/Metac.scala
  semanticdb/metac/src/main/scala/scala/meta/internal/metac/Main.scala
  semanticdb/metac/src/main/scala/scala/meta/metac/Reporter.scala
  semanticdb/metac/src/main/scala/scala/meta/metac/Settings.scala
  semanticdb/metacp/src/main/scala/scala/meta/cli/Metacp.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Javacp.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Checksum.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Index.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Settings.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/ToplevelClassfile.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/ToplevelInfos.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/package.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalacp.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalalib.scala
  semanticdb/metacp/src/main/scala/scala/meta/metacp/Reporter.scala
  semanticdb/metacp/src/main/scala/scala/meta/metacp/Settings.scala
  semanticdb/metap/src/main/scala/scala/meta/cli/Metap.scala
  semanticdb/metap/src/main/scala/scala/meta/internal/metap/Main.scala
  semanticdb/metap/src/main/scala/scala/meta/internal/metap/Settings.scala
  semanticdb/metap/src/main/scala/scala/meta/metap/Format.scala
  semanticdb/metap/src/main/scala/scala/meta/metap/Reporter.scala
  semanticdb/metap/src/main/scala/scala/meta/metap/Settings.scala
  tests/jvm/src/test/resources/highlevel.expect
  tests/jvm/src/test/resources/lowlevel.expect
  tests/jvm/src/test/resources/metac.owners
  tests/jvm/src/test/resources/metacp.expect
  tests/jvm/src/test/resources/metacp.owners
  tests/jvm/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/cli/BaseCliSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/cli/CliSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/metacp/BaseMetacpSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpCacheSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpCrashSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/metacp/SignatureSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/MetacScalaLibrary.scala
  tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
Labels: Metacp

#1399 Add new expect test to check diff between metacp and metac.
  .scalafmt.conf
  semanticdb/integration/src/main/java/com/javacp/MetacJava.java
  semanticdb/integration/src/main/scala/example/MetacJava.scala
  tests/jvm/src/test/resources/highlevel.expect
  tests/jvm/src/test/resources/lowlevel.expect
  tests/jvm/src/test/resources/metac-metacp.diff
  tests/jvm/src/test/resources/metac.owners
  tests/jvm/src/test/resources/metacp.expect
  tests/jvm/src/test/resources/metacp.owners
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala
Labels: Metac, Metacp

#1395 First stab at semanticidx support for metac
  build.sbt
  langmeta/langmeta/js/src/main/scala/org/langmeta/internal/io/PlatformFileIO.scala
  langmeta/langmeta/jvm/src/main/scala/org/langmeta/internal/io/PlatformFileIO.scala
  langmeta/langmeta/shared/src/main/scala/org/langmeta/internal/io/FileIO.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/index/Index.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/ToplevelClassfile.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/ToplevelInfos.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DatabaseOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DocumentOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPipeline.scala
  tests/jvm/src/test/resources/index.expect
  tests/jvm/src/test/resources/metac-metacp.expect.diff
  tests/jvm/src/test/resources/metac-metacp.index.diff
  tests/jvm/src/test/resources/metacp.index
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala
Labels: Metac

#1414 Synchronize Javacp and Metac on several fronts
  semanticdb/integration/src/main/java/com/javacp/MetacJava.java
  semanticdb/integration/src/main/scala/example/MetacJava.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Javacp.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DenotationOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SymbolOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TypeOps.scala
  tests/jvm/src/test/resources/highlevel.expect
  tests/jvm/src/test/resources/lowlevel.expect
  tests/jvm/src/test/resources/metac-metacp.expect.diff
  tests/jvm/src/test/resources/metac.owners
  tests/jvm/src/test/resources/metacp.expect
  tests/jvm/src/test/resources/metacp.owners
Labels: Javacp, Metac

#1416 Assorted fixes and improvements
  langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/Flags.scala
  langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala
  semanticdb/integration/src/main/java/com/javacp/Interface.java
  semanticdb/integration/src/main/java/com/javacp/Test.java
  semanticdb/integration/src/main/scala/example/MetacJava.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Javacp.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalacp.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalalib.scala
  semanticdb/metap/src/main/scala/scala/meta/internal/metap/Main.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DenotationOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SymbolOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TypeOps.scala
  semanticdb/semanticdb3/semanticdb3.md
  semanticdb/semanticdb3/semanticdb3.proto
  tests/jvm/src/test/resources/highlevel.expect
  tests/jvm/src/test/resources/lowlevel.expect
  tests/jvm/src/test/resources/metac-metacp.expect.diff
  tests/jvm/src/test/resources/metac-metacp.index.diff
  tests/jvm/src/test/resources/metac.owners
  tests/jvm/src/test/resources/metacp.expect
  tests/jvm/src/test/resources/metacp.index
  tests/jvm/src/test/resources/metacp.owners
  tests/jvm/src/test/resources/scalalib.expect
  tests/jvm/src/test/scala-2.12/scala/meta/tests/semanticdb/OverridesSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/cli/CliSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/InteractiveSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala
  tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
Labels: Spec

#1422 Further work on the spec
  langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/Flags.scala
  langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/Symbol.scala
  langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala
  semanticdb/integration/src/main/java/com/javacp/Coin.java
  semanticdb/integration/src/main/scala/example/MetacJava.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/index/Index.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Javacp.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalacp.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalalib.scala
  semanticdb/metap/src/main/scala/scala/meta/internal/metap/Main.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DenotationOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/NameOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SymbolOps.scala
  semanticdb/semanticdb3/semanticdb3.md
  semanticdb/semanticdb3/semanticdb3.proto
  tests/jvm/src/test/resources/highlevel.expect
  tests/jvm/src/test/resources/index.expect
  tests/jvm/src/test/resources/lowlevel.expect
  tests/jvm/src/test/resources/metac-metacp.expect.diff
  tests/jvm/src/test/resources/metac-metacp.index.diff
  tests/jvm/src/test/resources/metac.owners
  tests/jvm/src/test/resources/metacp.expect
  tests/jvm/src/test/resources/metacp.index
  tests/jvm/src/test/resources/metacp.owners
  tests/jvm/src/test/resources/scalalib.expect
  tests/jvm/src/test/scala-2.12/scala/meta/tests/semanticdb/MemberSuite.scala
  tests/jvm/src/test/scala-2.12/scala/meta/tests/semanticdb/OverridesSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/cli/CliSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/InteractiveSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala
  tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
Labels: Spec

#1430 Centralize symbol construction and deconstruction as much as possible
  langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/Symbol.scala
  langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/index/Index.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Javacp.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalacp.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DocumentOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/NameOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SymbolOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TypeOps.scala
  semanticdb/semanticdb3/semanticdb3.md
  semanticdb/semanticdb3/src/main/scala/scala/meta/internal/semanticdb3/Scala.scala
  tests/jvm/src/test/resources/highlevel.expect
  tests/jvm/src/test/resources/lowlevel.expect
  tests/jvm/src/test/resources/metac-metacp.expect.diff
  tests/jvm/src/test/resources/metacp.expect
  tests/jvm/src/test/resources/metacp.owners
  tests/jvm/src/test/scala/scala/meta/tests/metacp/BaseMetacpSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/InteractiveSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala
  tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
Labels: Spec

#1401 Progress towards ammonite support
  langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/vfs/SemanticdbPaths.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ConfigOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DocumentOps.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/HijackAnalyzer.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPipeline.scala
  semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPlugin.scala
Labels: Metac

#1434 Add a dependency on pprint.
  build.sbt
Labels: Build

#1438 Fix 1435 and 1437
  semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalacp.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalalib.scala
  tests/jvm/src/test/resources/metac-metacp.expect.diff
  tests/jvm/src/test/resources/metacp.expect
  tests/jvm/src/test/resources/scalalib.expect
  tests/jvm/src/test/scala/scala/meta/tests/metacp/BaseMetacpSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpCacheSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpCrashSuite.scala
Labels: Scalacp

#1453 Remove semanticdb-sbt from the list of supported projects
  RELEASING.md
Labels: Docs

#1452 Add Play framework to MetacpCrashSuite
  tests/jvm/src/test/scala/scala/meta/tests/metacp/BaseMetacpSuite.scala
  tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpCrashSuite.scala
Labels: Scalacp

#1459 Fill Java section of the SemanticDB specification, take two
  semanticdb/integration/src/main/java/com/javacp/Test.java
  semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Javacp.scala
  semanticdb/semanticdb3/semanticdb3.md
  tests/jvm/src/test/resources/metacp.expect
  tests/jvm/src/test/resources/metacp.owners
Labels: Spec

#1458 Fix #1392
  semanticdb/integration/src/main/scala/example/Types.scala
  semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalacp.scala
  tests/jvm/src/test/resources/highlevel.expect
  tests/jvm/src/test/resources/lowlevel.expect
  tests/jvm/src/test/resources/metac-metacp.expect.diff
  tests/jvm/src/test/resources/metac.owners
  tests/jvm/src/test/resources/metacp.expect
  tests/jvm/src/test/resources/metacp.owners
Labels: Scalacp

#1465 Update RELEASING.md to reflect recent updates to reality
  RELEASING.md
Labels: Docs
